project_id = "mfzlzeasbgsnrttjrhza"

[functions.handwriting-recognition]
verify_jwt = true

[functions.speech-to-text]
verify_jwt = true

[functions.generate-rubric]
verify_jwt = true

[functions.translate]
verify_jwt = true

[functions.grade-submission]
verify_jwt = true
